name: simple_beautiful_checklist_exercise
description: "A small but beautiful flutter checklist app to practice using SharedPreferences"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  uuid: ^4.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
